{{- if .Values.serviceAccount.create }}
{{- if .Values.serviceAccount.perDeployment }}
{{- range .Values.apiDeployments }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "astra.fullname" $ }}-{{ .name }}
  labels:
    app.kubernetes.io/name: {{ include "astra.name" $ }}
    astra.trust-domain: {{ .name | quote }}
{{- end }}
{{- range .Values.controlPlaneDeployments }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "astra.fullname" $ }}-{{ .name }}
  labels:
    app.kubernetes.io/name: {{ include "astra.name" $ }}
    astra.trust-domain: {{ .name | quote }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "astra.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "astra.name" . }}
    astra.component: migration
{{- else }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "astra.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "astra.name" . }}
{{- end }}
{{- end }}
